// Quiz系统部署ubuntu/quiz 本地/admin-frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <el-card class="login-card">
      <div class="login-title">
        <h2>Quiz 管理系统</h2>
      </div>
      <el-form ref="loginForm" :model="loginForm" :rules="loginRules" label-width="80px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="loginForm.username" placeholder="请输入用户名"></el-input>
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="loginForm.password" placeholder="请输入密码" type="password" @keyup.enter.native="handleLogin"></el-input>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" :loading="loading" @click="handleLogin" style="width: 100%">登录</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script>
export default {
  name: 'Login',
  data() {
    return {
      loginForm: {
        username: '',
        password: ''
      },
      loginRules: {
        username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
        password: [{ required: true, message: '请输入密码', trigger: 'blur' }]
      },
      loading: false
    }
  },
  methods: {
    handleLogin() {
      this.$refs.loginForm.validate(valid => {
        if (valid) {
          this.loading = true
          this.$axios.post('/admin/login', this.loginForm)
            .then(response => {
              this.loading = false
              const res = response.data
              if (res.code === 1) {
                // 检查用户是否是管理员
                // 这里假设后端返回的token中包含了用户角色信息，并且只有管理员角色能够登录
                localStorage.setItem('admin_token', res.data)
                
                // 跳转到首页或重定向页面
                const redirect = this.$route.query.redirect || '/'
                this.$router.push(redirect)
              } else {
                this.$message.error(res.msg || '登录失败，请检查您的用户名和密码')
              }
            })
            .catch(error => {
              this.loading = false
              this.$message.error('登录失败，请稍后重试')
              console.error(error)
            })
        }
      })
    }
  }
}
</script>

<style scoped>
.login-container {
  width: 100%;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #f5f7fa;
}

.login-card {
  width: 400px;
}

.login-title {
  text-align: center;
  margin-bottom: 20px;
}

.login-title h2 {
  font-weight: 500;
}
</style>

// QuizReact/src/pages/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Form, Input, Button, Card, message } from 'antd';

const Login = () => {
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const onFinish = (values) => {
    setLoading(true);
    // 模拟登录验证
    setTimeout(() => {
      if (values.username === 'admin' && values.password === 'admin123') {
        localStorage.setItem('admin_token', 'mock_token_123');
        localStorage.setItem('admin_username', values.username);
        message.success('登录成功');
        navigate('/');
      } else {
        message.error('用户名或密码错误');
      }
      setLoading(false);
    }, 500);
  };

  return (
    <div style={styles.container}>
      <Card style={styles.card}>
        <h2 style={styles.title}>Quiz 管理系统</h2>
        <Form name="login" onFinish={onFinish} labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
          <Form.Item label="用户名" name="username" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input placeholder="请输入用户名" />
          </Form.Item>
          <Form.Item label="密码" name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password placeholder="请输入密码" />
          </Form.Item>
          <Form.Item wrapperCol={{ offset: 6, span: 18 }}>
            <Button type="primary" htmlType="submit" loading={loading} block>
              登录
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  );
};

const styles = {
  container: {
    width: '100%',
    height: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f7fa',
  },
  card: { width: 400 },
  title: { textAlign: 'center', marginBottom: 24, fontWeight: 500 },
};

export default Login;
