// QuizReact/src/pages/Question.jsx
import React, { useState, useEffect } from 'react';
import { Table, Button, Input, Modal, Form, Radio, Space, Popconfirm, message, Divider } from 'antd';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import { mockQuestions } from '../data/mockData';

const Question = () => {
  const [questions, setQuestions] = useState([]);
  const [filteredQuestions, setFilteredQuestions] = useState([]);
  const [keyword, setKeyword] = useState('');
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [isEdit, setIsEdit] = useState(false);
  const [editingQuestion, setEditingQuestion] = useState(null);
  const [form] = Form.useForm();
  const [correctIndex, setCorrectIndex] = useState(-1);
  const [answers, setAnswers] = useState([{ text: '' }, { text: '' }, { text: '' }, { text: '' }]);
  const [pagination, setPagination] = useState({ current: 1, pageSize: 5, total: 0 });

  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setQuestions([...mockQuestions]);
      setFilteredQuestions([...mockQuestions]);
      setPagination(prev => ({ ...prev, total: mockQuestions.length }));
      setLoading(false);
    }, 300);
  }, []);

  const handleSearch = () => {
    const filtered = questions.filter(q => q.question.toLowerCase().includes(keyword.toLowerCase()));
    setFilteredQuestions(filtered);
    setPagination(prev => ({ ...prev, current: 1, total: filtered.length }));
  };

  const openAddModal = () => {
    setIsEdit(false);
    setEditingQuestion(null);
    setAnswers([{ text: '' }, { text: '' }, { text: '' }, { text: '' }]);
    setCorrectIndex(-1);
    form.resetFields();
    setModalVisible(true);
  };

  const openEditModal = (record) => {
    setIsEdit(true);
    setEditingQuestion(record);
    form.setFieldsValue({ question: record.question });
    setAnswers([...record.answers.map(a => ({ text: a.text }))]);
    setCorrectIndex(record.answers.findIndex(a => a.correct));
    setModalVisible(true);
  };

  const handleSubmit = () => {
    form.validateFields().then(values => {
      if (correctIndex < 0) { message.warning('请选择一个正确答案'); return; }
      const filteredAnswers = answers.filter(a => a.text.trim() !== '');
      if (filteredAnswers.length < 2) { message.warning('至少需要两个选项'); return; }
      if (!filteredAnswers[correctIndex] || !filteredAnswers[correctIndex].text.trim()) {
        message.warning('正确答案的选项内容不能为空'); return;
      }
      const finalAnswers = filteredAnswers.map((a, i) => ({ text: a.text, correct: i === correctIndex }));

      if (isEdit) {
        const newQuestions = questions.map(q => q.id === editingQuestion.id ? { ...q, question: values.question, answers: finalAnswers } : q);
        setQuestions(newQuestions);
        setFilteredQuestions(newQuestions.filter(q => q.question.toLowerCase().includes(keyword.toLowerCase())));
        message.success('修改题目成功');
      } else {
        const newQuestion = { id: Math.max(...questions.map(q => q.id)) + 1, question: values.question, answers: finalAnswers };
        const newQuestions = [...questions, newQuestion];
        setQuestions(newQuestions);
        setFilteredQuestions(newQuestions);
        setPagination(prev => ({ ...prev, total: newQuestions.length }));
        message.success('添加题目成功');
      }
      setModalVisible(false);
    });
  };

  const handleDelete = (id) => {
    const newQuestions = questions.filter(q => q.id !== id);
    setQuestions(newQuestions);
    setFilteredQuestions(newQuestions.filter(q => q.question.toLowerCase().includes(keyword.toLowerCase())));
    setPagination(prev => ({ ...prev, total: newQuestions.length }));
    message.success('删除题目成功');
  };

  const addOption = () => setAnswers([...answers, { text: '' }]);
  const removeOption = (index) => {
    const newAnswers = answers.filter((_, i) => i !== index);
    setAnswers(newAnswers);
    if (correctIndex === index) setCorrectIndex(-1);
    else if (correctIndex > index) setCorrectIndex(correctIndex - 1);
  };
  const updateOption = (index, value) => {
    const newAnswers = [...answers];
    newAnswers[index].text = value;
    setAnswers(newAnswers);
  };

  const columns = [
    { title: 'ID', dataIndex: 'id', width: 80 },
    { title: '题目内容', dataIndex: 'question', ellipsis: true },
    {
      title: '所有选项', width: 300,
      render: (_, record) => record.answers?.map((a, i) => <span key={i} style={{ marginRight: 10 }}>{String.fromCharCode(65 + i)}. {a.text}</span>) || '-',
    },
    {
      title: '正确选项', width: 100,
      render: (_, record) => record.answers?.map((a, i) => a.correct ? String.fromCharCode(65 + i) : '').filter(x => x).join(', ') || '-',
    },
    {
      title: '操作', width: 160,
      render: (_, record) => (
        <Space>
          <Button size="small" type="primary" onClick={() => openEditModal(record)}>编辑</Button>
          <Popconfirm title="确定要删除该题目吗?" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" danger>删除</Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <h2 style={{ marginBottom: 20 }}>题目管理</h2>
      <Space style={{ marginBottom: 20 }}>
        <Input placeholder="请输入题目关键词" value={keyword} onChange={e => setKeyword(e.target.value)} style={{ width: 200 }} />
        <Button type="primary" onClick={handleSearch}>搜索</Button>
        <Button type="primary" className="add-btn" onClick={openAddModal}>添加题目</Button>
      </Space>
      <Table columns={columns} dataSource={filteredQuestions} rowKey="id" loading={loading}
        pagination={{ ...pagination, showSizeChanger: true, pageSizeOptions: ['5', '10', '20', '50'], showTotal: t => `共 ${t} 条`,
          onChange: (page, pageSize) => setPagination({ ...pagination, current: page, pageSize }) }} />

      <Modal title={isEdit ? '编辑题目' : '添加题目'} open={modalVisible} onCancel={() => setModalVisible(false)} onOk={handleSubmit} width={600} destroyOnClose>
        <Form form={form} labelCol={{ span: 4 }} wrapperCol={{ span: 20 }}>
          <Form.Item label="题目内容" name="question" rules={[{ required: true, message: '请输入题目内容' }]}>
            <Input.TextArea rows={3} placeholder="请输入题目内容" />
          </Form.Item>
          <Divider orientation="left">选项</Divider>
          {answers.map((answer, index) => (
            <div key={index} style={{ display: 'flex', alignItems: 'center', marginBottom: 12 }}>
              <span style={{ width: 60 }}>选项 {index + 1}</span>
              <Input value={answer.text} onChange={e => updateOption(index, e.target.value)} placeholder="请输入选项内容" style={{ flex: 1 }} />
              <Radio checked={correctIndex === index} onChange={() => setCorrectIndex(index)} style={{ marginLeft: 10 }}>正确答案</Radio>
              {answers.length > 2 && <Button type="text" danger icon={<DeleteOutlined />} onClick={() => removeOption(index)} />}
            </div>
          ))}
          <Button type="dashed" onClick={addOption} icon={<PlusOutlined />}>添加选项</Button>
        </Form>
      </Modal>
    </div>
  );
};

export default Question;

// Quiz系统部署ubuntu/quiz 部署/admin-frontend/src/views/Question.vue
<template>
  <div class="question-container">
    <div class="page-header">
      <h2>题目管理</h2>
    </div>
    
    <!-- 搜索区域 -->
    <el-form :inline="true" :model="searchForm" class="search-form">
      <el-form-item>
        <el-input v-model="searchForm.keyword" placeholder="请输入题目关键词"></el-input>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="searchQuestions">搜索</el-button>
        <el-button type="success" @click="openAddDialog">添加题目</el-button>
      </el-form-item>
    </el-form>
    
    <!-- 题目表格 -->
    <el-table :data="questionList" style="width: 100%" v-loading="loading">
      <el-table-column prop="id" label="ID" width="80"></el-table-column>
      <el-table-column prop="question" label="题目内容" show-overflow-tooltip></el-table-column>
      <el-table-column label="所有选项" min-width="200">
        <template slot-scope="scope">
          <div v-if="scope.row.answers && scope.row.answers.length">
            <span v-for="(answer, index) in scope.row.answers" :key="index" style="margin-right: 10px;">
              {{ String.fromCharCode(65 + index) }}. {{ answer.text }}
            </span>
          </div>
          <span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column label="正确选项" width="120">
        <template slot-scope="scope">
          <span v-if="scope.row.answers && scope.row.answers.length">
            {{ scope.row.answers.map((a, i) => a.correct ? String.fromCharCode(65 + i) : '').filter(x => x).join(', ') || '-' }}
          </span>
          <span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200">
        <template slot-scope="scope">
          <el-button size="mini" type="primary" @click="editQuestion(scope.row)">编辑</el-button>
          <el-button size="mini" type="danger" @click="confirmDelete(scope.row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    
    <!-- 分页 -->
    <div class="pagination-container">
      <el-pagination
        background
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
        :current-page.sync="pagination.currentPage"
        :page-sizes="[5, 10, 20, 50]"
        :page-size="pagination.pageSize"
        layout="total, sizes, prev, pager, next, jumper"
        :total="pagination.total">
      </el-pagination>
    </div>
    
    <!-- 添加/编辑题目对话框 -->
    <el-dialog :title="dialogTitle" :visible.sync="dialogVisible" width="60%">
      <el-form ref="questionForm" :model="questionForm" :rules="questionRules" label-width="100px">
        <el-form-item label="题目内容" prop="question">
          <el-input v-model="questionForm.question" type="textarea" :rows="4" placeholder="请输入题目内容"></el-input>
        </el-form-item>
        
        <el-divider content-position="left">选项</el-divider>
        
        <div v-for="(option, index) in questionForm.answers" :key="index" class="option-item">
          <el-form-item :label="'选项 ' + (index + 1)" :prop="'answers.' + index + '.text'" :rules="[
            { required: true, message: '请输入选项内容', trigger: 'blur' }
          ]">
            <div class="option-row">
              <el-input v-model="option.text" placeholder="请输入选项内容"></el-input>
              <el-radio :label="index" v-model="correctAnswerIndex" style="margin-left: 10px;">正确答案</el-radio>
              <el-button v-if="questionForm.answers.length > 2" type="danger" icon="el-icon-delete" circle size="mini" @click="removeOption(index)" style="margin-left: 10px;"></el-button>
            </div>
          </el-form-item>
        </div>
        
        <el-form-item>
          <el-button type="primary" @click="addOption" icon="el-icon-plus">添加选项</el-button>
        </el-form-item>
      </el-form>
      <div slot="footer">
        <el-button @click="dialogVisible = false">取 消</el-button>
        <el-button type="primary" @click="submitQuestion" :loading="submitLoading">确 定</el-button>
      </div>
    </el-dialog>
    
  </div>
</template>

<script>
export default {
  name: 'Question',
  data() {
    return {
      // 题目列表
      questionList: [],
      loading: false,
      
      // 分页
      pagination: {
        currentPage: 1,
        pageSize: 5,
        total: 0
      },
      
      // 搜索
      searchForm: {
        keyword: ''
      },
      
      // 对话框
      dialogVisible: false,
      dialogTitle: '添加题目',
      submitLoading: false,
      isEdit: false,
      
      // 题目表单
      questionForm: {
        id: null,
        question: '',
        answers: [
          { text: '', correct: false },
          { text: '', correct: false },
          { text: '', correct: false },
          { text: '', correct: false }
        ]
      },
      correctAnswerIndex: -1,
      questionRules: {
        question: [
          { required: true, message: '请输入题目内容', trigger: 'blur' }
        ]
      }
    };
  },
  created() {
    this.fetchQuestionList();
  },
  methods: {
    // 获取题目列表
    fetchQuestionList() {
      this.loading = true;
      const params = {
        page: this.pagination.currentPage,
        pageSize: this.pagination.pageSize,
        keyword: this.searchForm.keyword
      };
      
      this.$axios.get('/question/list', { params })
        .then(response => {
          const res = response.data;
          if (res.code === 1) {
            this.questionList = res.data.records || res.data.list || res.data;
            this.pagination.total = res.data.total || this.questionList.length;
          } else {
            this.$message.error(res.msg || '获取题目列表失败');
          }
          this.loading = false;
        })
        .catch(error => {
          console.error(error);
          this.$message.error('获取题目列表失败');
          this.loading = false;
        });
    },
    
    // 搜索题目
    searchQuestions() {
      this.pagination.currentPage = 1;
      this.fetchQuestionList();
    },
    
    // 分页大小改变
    handleSizeChange(val) {
      this.pagination.pageSize = val;
      this.fetchQuestionList();
    },
    
    // 当前页改变
    handleCurrentChange(val) {
      this.pagination.currentPage = val;
      this.fetchQuestionList();
    },
    
    // 打开添加题目对话框
    openAddDialog() {
      this.isEdit = false;
      this.dialogTitle = '添加题目';
      this.questionForm = {
        id: null,
        question: '',
        answers: [
          { text: '', correct: false },
          { text: '', correct: false },
          { text: '', correct: false },
          { text: '', correct: false }
        ]
      };
      this.correctAnswerIndex = -1;
      this.dialogVisible = true;
      // 重置表单验证
      if (this.$refs.questionForm) {
        this.$nextTick(() => {
          this.$refs.questionForm.clearValidate();
        });
      }
    },
    
    // 编辑题目
    editQuestion(row) {
      this.isEdit = true;
      this.dialogTitle = '编辑题目';
      // 获取题目详情
      this.$axios.get(`/question/detail/${row.id}`)
        .then(response => {
          const res = response.data;
          if (res.code === 1) {
            this.questionForm = {
              id: res.data.id,
              question: res.data.question,
              answers: [...res.data.answers] // 确保是新数组
            };
            
            // 找到正确答案的索引
            this.correctAnswerIndex = this.questionForm.answers.findIndex(a => a.correct);
            
            // 确保至少有4个选项
            while (this.questionForm.answers.length < 4) {
              this.questionForm.answers.push({ text: '', correct: false });
            }
            
            this.dialogVisible = true;
          } else {
            this.$message.error(res.msg || '获取题目详情失败');
          }
        })
        .catch(error => {
          console.error(error);
          this.$message.error('获取题目详情失败');
        });
    },
    
    // 添加选项
    addOption() {
      this.questionForm.answers.push({ text: '', correct: false });
    },
    
    // 移除选项
    removeOption(index) {
      this.questionForm.answers.splice(index, 1);
    },
    
    // 提交题目
    submitQuestion() {
      this.$refs.questionForm.validate(valid => {
        if (valid) {
          // 验证是否选择了正确答案
          if (this.correctAnswerIndex < 0) {
            this.$message.warning('请选择一个正确答案');
            return;
          }
          
          // 根据correctAnswerIndex设置correct属性
          this.questionForm.answers.forEach((a, i) => {
            a.correct = (i === this.correctAnswerIndex);
          });
          
          // 过滤掉空选项
          const filteredAnswers = this.questionForm.answers.filter(a => a.text.trim() !== '');
          
          // 检查正确答案是否在过滤后的选项中
          const correctInFiltered = filteredAnswers.some(a => a.correct);
          if (!correctInFiltered) {
            this.$message.warning('正确答案的选项内容不能为空');
            return;
          }
          
          this.questionForm.answers = filteredAnswers;
          
          // 验证至少有两个选项
          if (this.questionForm.answers.length < 2) {
            this.$message.warning('至少需要两个选项');
            return;
          }
          
          this.submitLoading = true;
          const url = this.isEdit ? '/question/update' : '/question/add';
          this.$axios.post(url, this.questionForm)
            .then(response => {
              const res = response.data;
              if (res.code === 1) {
                this.$message.success(this.isEdit ? '修改题目成功' : '添加题目成功');
                this.dialogVisible = false;
                this.fetchQuestionList();
              } else {
                this.$message.error(res.msg || (this.isEdit ? '修改题目失败' : '添加题目失败'));
              }
              this.submitLoading = false;
            })
            .catch(error => {
              console.error(error);
              this.$message.error(this.isEdit ? '修改题目失败' : '添加题目失败');
              this.submitLoading = false;
            });
        }
      });
    },
    
    // 确认删除题目
    confirmDelete(row) {
      this.$confirm('确定要删除该题目吗?', '提示', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        this.deleteQuestion(row.id);
      }).catch(() => {});
    },
    
    // 删除题目
    deleteQuestion(id) {
      this.$axios.delete(`/question/delete/${id}`)
        .then(response => {
          const res = response.data;
          if (res.code === 1) {
            this.$message.success('删除题目成功');
            this.fetchQuestionList();
          } else {
            this.$message.error(res.msg || '删除题目失败');
          }
        })
        .catch(error => {
          console.error(error);
          this.$message.error('删除题目失败');
        });
    }
  }
};
</script>

<style scoped>
.question-container {
  padding: 20px;
}

.page-header {
  margin-bottom: 20px;
}

.search-form {
  margin-bottom: 20px;
}

.pagination-container {
  margin-top: 20px;
  text-align: right;
}

.option-item {
  margin-bottom: 15px;
}

.option-row {
  display: flex;
  align-items: center;
}
</style>
